# -*- coding: utf-8 -*-
"""AER850_Project3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_OuVqCVVb_1qM0QAoqljWZ7X5HB09Foi
"""

from google.colab import drive
import cv2
import numpy as np
import matplotlib.pyplot as plt
from ultralytics import YOLO

# Step 1: Load the Pretrained YOLOv8 Nano Model
model = YOLO('yolov8n.pt')  # YOLOv8 Nano (pretrained weights)

# Step 2: Train the Model

model.train(

   data= "/content/drive/MyDrive/850 Project 3/Project 3 Data/data/data.yaml",
   epochs=40,
   batch=6,
   imgsz=900,
   name='my_model',
   workers=4
   )

# Step 3: Evaluate the Model
# After training, use validation images to evaluate performance
metrics = model.val()
print(metrics)

#Step 3 from Project
eval_path = "/content/drive/MyDrive/850 Project 3/Project 3 Data/data/evaluation"
evaluation_results=model.predict(source= eval_path,save=True)

!pip install ultralytics